# Generated by Django 3.1.2 on 2020-10-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algomination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
