# Generated by Django 3.1.2 on 2020-11-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algomination', '0002_auto_20201028_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
