# Generated by Django 4.2.7 on 2025-07-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('algorithm_type', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=20)),
                ('time_complexity', models.CharField(max_length=20)),
                ('space_complexity', models.CharField(max_length=20)),
                ('pseudocode', models.TextField()),
                ('implementation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
